// posts
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_POSTS_BY_CATEGORY_SUCCESS = 'LOAD_POSTS_BY_CATEGORY_SUCCESS';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const READ_POST_SUCCESS = 'READ_POST_SUCCESS';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const UPDATE_POST_UP_VOTE_SUCCESS = 'UPDATE_POST_UP_VOTE_SUCCESS';

// categories
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';

// nav
export const NAV_ACTIVE_CATEGORY = 'NAV_ACTIVE_CATEGORY';

// comments
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENTS_SUCCESS';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';

// app
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
export const RESET_DETAIL = 'RESET_DETAIL';