// posts
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_POSTS_BY_CATEGORY_SUCCESS = 'LOAD_POSTS_BY_CATEGORY_SUCCESS';

// categories
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';

// nav
export const NAV_ACTIVE_CATEGORY_SUCCESS = 'NAV_ACTIVE_CATEGORY_SUCCESS';

// comments
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';

// app
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';