// posts
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';

// categories
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';

// comments
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';