// decks
export const LOAD_DECKS_SUCCESS = 'LOAD_DECKS_SUCCESS';
export const LOAD_DECKS_ERROR = 'LOAD_DECKS_ERROR';

export const CREATE_DECK_SUCCESS = 'CREATE_DECK_SUCCESS';
export const CREATE_DECK_ERROR = 'CREATE_DECK_ERROR';

export const UPDATE_DECK_SUCCESS = 'UPDATE_DECK_SUCCESS';
export const UPDATE_DECK_ERROR = 'UPDATE_DECK_ERROR';

export const DELETE_DECK_SUCCESS = 'DELETE_DECK_SUCCESS';
export const DELETE_DECK_ERROR = 'DELETE_DECK_ERROR';

export const CREATE_NEW_DECK = 'CREATE_NEW_DECK';
export const LOAD_DECKS = 'LOAD_DECKS';

// Storage
export const STORAGE_REQUEST = 'STORAGE_REQUEST';